# Generated by Django 5.2.3 on 2025-06-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('parent_guardian_name', models.CharField(max_length=100)),
                ('student_contact', models.CharField(max_length=15)),
                ('parent_contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=20, unique=True)),
                ('aadhar_photo', models.URLField(blank=True)),
                ('school_college_name', models.CharField(max_length=150)),
                ('class_grade', models.CharField(max_length=50)),
                ('board_university', models.CharField(max_length=100)),
                ('academic_records', models.TextField()),
                ('medium_of_instruction', models.CharField(max_length=50)),
                ('has_school_sslc', models.BooleanField(default=False)),
                ('sslc_board', models.CharField(blank=True, max_length=50)),
                ('sslc_year', models.CharField(blank=True, max_length=10)),
                ('sslc_percentage', models.CharField(blank=True, max_length=10)),
                ('sslc_school', models.CharField(blank=True, max_length=100)),
                ('has_hsc', models.BooleanField(default=False)),
                ('hsc_board', models.CharField(blank=True, max_length=50)),
                ('hsc_year', models.CharField(blank=True, max_length=10)),
                ('hsc_percentage', models.CharField(blank=True, max_length=10)),
                ('hsc_college', models.CharField(blank=True, max_length=100)),
                ('hsc_stream', models.CharField(blank=True, max_length=50)),
                ('has_ug', models.BooleanField(default=False)),
                ('ug_course', models.CharField(blank=True, max_length=50)),
                ('ug_college', models.CharField(blank=True, max_length=100)),
                ('ug_year', models.CharField(blank=True, max_length=10)),
                ('ug_percentage', models.CharField(blank=True, max_length=10)),
                ('ug_specialization', models.CharField(blank=True, max_length=100)),
                ('has_pg', models.BooleanField(default=False)),
                ('pg_course', models.CharField(blank=True, max_length=50)),
                ('pg_college', models.CharField(blank=True, max_length=100)),
                ('pg_year', models.CharField(blank=True, max_length=10)),
                ('pg_percentage', models.CharField(blank=True, max_length=10)),
                ('pg_specialization', models.CharField(blank=True, max_length=100)),
                ('target_exams', models.CharField(max_length=200)),
                ('preferred_subjects', models.CharField(max_length=200)),
                ('preparation_level', models.CharField(max_length=50)),
                ('coaching_package', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('photo', models.URLField(blank=True)),
            ],
        ),
    ]
