# Generated by Django 5.2.3 on 2025-06-29 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar_photo',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
