# Generated by Django 5.2.3 on 2025-06-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_aadhar_photo_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar_photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
