# Generated by Django 5.2.3 on 2025-07-12 06:24

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_student_aadhar_photo_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='aadhar_number',
            field=api.fields.EncryptedCharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
