# Generated by Django 5.2.3 on 2026-08-09 15:29

import api.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_student_aadhar_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('enrollment_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('roll_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_guardian_name', models.CharField(blank=True, max_length=100, null=True)),
                ('student_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('parent_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('aadhar_number', api.fields.EncryptedCharField(blank=True, max_length=200, null=True, unique=True)),
                ('aadhar_photo', models.TextField(blank=True, null=True)),
                ('school_college_name', models.CharField(blank=True, max_length=150, null=True)),
                ('class_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('board_university', models.CharField(blank=True, max_length=100, null=True)),
                ('academic_records', models.TextField(blank=True, null=True)),
                ('medium_of_instruction', models.CharField(blank=True, max_length=50, null=True)),
                ('has_school_sslc', models.BooleanField(blank=True, default=False)),
                ('sslc_board', models.CharField(blank=True, max_length=50, null=True)),
                ('sslc_year', models.CharField(blank=True, max_length=10, null=True)),
                ('sslc_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('sslc_school', models.CharField(blank=True, max_length=100, null=True)),
                ('has_hsc', models.BooleanField(blank=True, default=False)),
                ('hsc_board', models.CharField(blank=True, max_length=50, null=True)),
                ('hsc_year', models.CharField(blank=True, max_length=10, null=True)),
                ('hsc_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('hsc_college', models.CharField(blank=True, max_length=100, null=True)),
                ('hsc_stream', models.CharField(blank=True, max_length=50, null=True)),
                ('has_ug', models.BooleanField(blank=True, default=False)),
                ('ug_course', models.CharField(blank=True, max_length=50, null=True)),
                ('ug_college', models.CharField(blank=True, max_length=100, null=True)),
                ('ug_year', models.CharField(blank=True, max_length=10, null=True)),
                ('ug_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('ug_specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('has_pg', models.BooleanField(blank=True, default=False)),
                ('pg_course', models.CharField(blank=True, max_length=50, null=True)),
                ('pg_college', models.CharField(blank=True, max_length=100, null=True)),
                ('pg_year', models.CharField(blank=True, max_length=10, null=True)),
                ('pg_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('pg_specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('target_exams', models.CharField(blank=True, max_length=200, null=True)),
                ('preferred_subjects', models.CharField(blank=True, max_length=200, null=True)),
                ('preparation_level', models.CharField(blank=True, max_length=50, null=True)),
                ('coaching_package', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
